### ISSUE TITLE
Require server priv

### ISSUE THREAD

**Issue by aerozoic** [minetest-mods/privilegeareas#1]
Shouldn't the /privareas command require server priv?
:large_orange_diamond:

**Comment by aerozoic** [comment]
Yep, i've had this installed on my server for a few weeks now but never tested it until now. Using an account with basic privs i used /privareas to grant myself privs priv which i then used to /grantme all. I guess i'm lucky i nobody else figured this out, lol. 
:large_orange_diamond:

**Comment by zeuner** [comment]
I think the "server" privilege is not too appropriate for what the command does. It's not really about server maintenance, and there may be scenarios where someone should be able to create privilege areas, but not to do things like shutting down the server.

**Comment by zeuner** [comment]
Great!

original message follows:

**Comment by aerozoic** [comment]
Perhaps i'm mistaken but what you suggest @zeuner doesn't seem possible. Anyone with privs priv can grant themselves server priv. So in that sense privs priv=server priv. Any player that is allowed to use the /privareas command can give themselves server priv. That is why i suggested server priv as the requirement.

🔶

**Comment by zeuner** [comment]
@aerozoic: Good point! In that sense, it makes no difference whether
to require "privs" or "server" currently. Still, I would regard the
/privareas functionality as being more similar to what the "privs"
privilege stands for, than what the "server" privilege stands for.

By the way, it may be worth considering to implement the privilege
granting through minetest.chatcommands["grant"].func (and revocations
accordingly), thereby limiting what the area can do to the privileges
the player who created the area can manipulate.

original message follows:
